# ============================================================================
# sqlite
# ============================================================================
sqlite.driverClassName=org.sqlite.JDBC
sqlite.database=jdspider
sqlite.url=jdbc:sqlite:jdspider.db

sqlite.defaultAutoCommit=true
sqlite.initialSize=1
sqlite.maxActive=60
sqlite.minIdle=1
sqlite.maxIdle=5
sqlite.maxWait=3000
sqlite.removeAbandoned=true
sqlite.removeAbandonedTimeout=1800
sqlite.testWhileIdle=true
sqlite.testOnBorrow=false
sqlite.testOnReturn=false
sqlite.validationQuery=select 1
sqlite.timeBetweenEvictionRunsMillis=30000
sqlite.numTestsPerEvictionRun=100
sqlite.filters=mergeStat
sqlite.logAbandoned=true
sqlite.minEvictableIdleTimeMillis=25200000
# ============================================================================
# mysql
# ============================================================================
mysql.driverClassName=com.mysql.jdbc.Driver
mysql.database=itil_0922
mysql.url=jdbc:mysql://172.17.21.188:3306/itil_0922?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
mysql.username=root
mysql.password=itil2016

mysql.defaultAutoCommit=true
mysql.initialSize=1
mysql.maxActive=60
mysql.minIdle=1
mysql.maxIdle=5
mysql.maxWait=3000
mysql.removeAbandoned=true
mysql.removeAbandonedTimeout=1800
mysql.testWhileIdle=true
mysql.testOnBorrow=false
mysql.testOnReturn=false
mysql.validationQuery=select 1
mysql.timeBetweenEvictionRunsMillis=30000
mysql.numTestsPerEvictionRun=100
mysql.filters=mergeStat
mysql.logAbandoned=true
mysql.minEvictableIdleTimeMillis=25200000
# ============================================================================
# Log
# ============================================================================
log.write2redis=false
log.log2usp=true
log.listname=system_log
# ============================================================================
# USP
# ============================================================================
#DEV
usp.configpath=D:\\dev\\spiderclient\\src\\resources\\uspapi.properties
#SIT
#usp.configpath=/usr/local/data/spider/uspapi.properties
# ============================================================================
# Redis
# ============================================================================
#DEV
#redis.addr=172.17.21.188
#TEST&SIT&PRD
redis.addr=127.0.0.1
redis.port=6379
# ============================================================================
# Message API
# ============================================================================
#TEST&SIT
#sms.url=http://172.17.21.188/message/messct/reviceMes
#PRD
sms.url=http://127.0.0.1/message/messct/reviceMes
# ============================================================================
# Zabbix API
# ============================================================================
#TEST&SIT
zabbix.url=http://10.1.20.253/api_jsonrpc.php
#PRD
#zabbix.url=http://10.0.19.30/api_jsonrpc.php
zabbix.account=lizhiqiang
zabbix.password=ucsmy1
zabbix.cachesize=100
# ============================================================================
# Auto Service
# ============================================================================
auto.freehostnameday=3
auto.freeallocipday=3
# ============================================================================
# Remind Service
# ============================================================================
remind.yellow=90
remind.red=30
# ============================================================================
# Vmware Api
# ============================================================================
vm.url=http://172.17.21.69:8001/vm-api
vm.charset=utf-8
# ============================================================================
# LDAP Api
# ============================================================================
#DEV
#SIT
ldap.url=LDAP://172.17.20.16:389
ldap.account=itsm_ad@wangjin.local
ldap.password=IIttssmm!!0
#ldap.searchbase="DC=wangjin,DC=local"
#PRD
#ldap.url=LDAP://10.0.19.1:389
#ldap.account=readdomain@ucs.com
#ldap.password=Ucs)^!(2017
#ldap.searchbase="OU=MSS,OU=RSA,DC=ucs,DC=com"
# ============================================================================
# RabbitMQ
# ============================================================================
#DEV
#mq.host=172.17.21.65
#mq.username=admin
#mq.password=admin123
#mq.port=5672
#PRD
mq.host=13.114.136.120
mq.username=admin
mq.password=olgeer
mq.port=5672
